---
- hosts: production
  gather_facts: true
  vars:
    web_env_path: /home/lina/subsawwy.com/web.env
    backend_env_path: /home/lina/subsawwy.com/backend.env

  tasks:
    - name: Check if env files exist
      ansible.builtin.stat:
        path: "{{ item }}"
      register: env_files
      with_items:
        - "{{ web_env_path }}"
        - "{{ backend_env_path }}"
      
    - name: Fail if env files don't exist
      fail:
        msg: "Required .env files not found. Please ensure both {{ web_env_path }} and {{ backend_env_path }} exist."
      when: not env_files.results[0].stat.exists or not env_files.results[1].stat.exists

    - name: Create network
      community.docker.docker_network:
        name: subsawwy_net
        driver: bridge
        state: present

    - name: Log into private registry
      community.docker.docker_login:
        registry_url: registry.keireira.com
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        reauthorize: true

    - name: Deploy frontend (SS-WEB)
      community.docker.docker_container:
        name: SS-WEB
        image: registry.keireira.com/subsawwy-web:latest
        state: started
        restart_policy: always
        recreate: true
        networks:
          - name: subsawwy_net
        ports:
          - "127.0.0.1:4200:80"
        env_file: "{{ web_env_path }}"
        labels:
          org.opencontainers.image.title: "Subsawwy WEB App"
          org.opencontainers.image.description: "app.subsawwy.com"
          org.opencontainers.image.authors: "Alena Dzhukich <mail@alena.red>"

    - name: Deploy backend (SS-API)
      community.docker.docker_container:
        name: SS-API
        image: registry.keireira.com/subsawwy-backend:latest
        state: started
        restart_policy: always
        recreate: true
        networks:
          - name: subsawwy_net
        ports:
          - "127.0.0.1:1337:1337"
        env_file: "{{ backend_env_path }}"

    - name: Deploy landing (SS-LANDING)
      community.docker.docker_container:
        name: SS-LANDING
        image: registry.keireira.com/subsawwy-landing:latest
        state: started
        restart_policy: always
        recreate: true
        networks:
          - name: subsawwy_net
        ports:
          - "127.0.0.1:4300:80"

    - name: Clean up old images
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: true