---
- hosts: production
  gather_facts: true
  vars:
    web_env_path: /home/lina/subsawwy.com/web.env
    backend_env_path: /home/lina/subsawwy.com/backend.env

  tasks:
    - name: Create network
      community.docker.docker_network:
        name: subsawwy_net
        driver: bridge
        state: present

    - name: Log into private registry
      community.docker.docker_login:
        registry_url: registry.keireira.com
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        reauthorize: true

    - name: Deploy landing (SS-LANDING)
      community.docker.docker_container:
        name: SS-LANDING
        image: registry.keireira.com/subsawwy-landing:latest
        state: started
        restart_policy: always
        pull: true
        recreate: true
        networks:
          - name: subsawwy_net
        ports:
          - "127.0.0.1:4300:80"

    - name: Clean up old images
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: true