---
- hosts: production
  gather_facts: true
  vars:
    web_env_path: /home/lina/subsawwy.com/web.env
    backend_env_path: /home/lina/subsawwy.com/backend.env

  tasks:
    - name: Check if env file exists
      ansible.builtin.stat:
        path: "{{ item }}"
      register: env_files
      with_items:
        - "{{ web_env_path }}"
      
    - name: Fail if env file don't exist
      fail:
        msg: "Required .env file not found. Please ensure {{ web_env_path }} exists."
      when: not env_files.results[0].stat.exists

    - name: Create network
      community.docker.docker_network:
        name: subsawwy_net
        driver: bridge
        state: present

    - name: Log into private registry
      community.docker.docker_login:
        registry_url: registry.keireira.com
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        reauthorize: true

    - name: Deploy frontend (PUPUPU-WEB)
      community.docker.docker_container:
        name: PUPUPU-WEB
        image: registry.keireira.com/subsawwy-web:latest
        state: started
        restart_policy: always
        pull: true
        recreate: true
        networks:
          - name: subsawwy_net
        ports:
          - "127.0.0.1:4200:80"
        env_file: "{{ web_env_path }}"
        labels:
          org.opencontainers.image.title: "Subsawwy WEB App"
          org.opencontainers.image.description: "app.subsawwy.com"
          org.opencontainers.image.authors: "Alena Dzhukich <mail@alena.red>"

    - name: Clean up old images
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: true