---
- hosts: production
  gather_facts: true
  vars:
    backend_env_path: /home/lina/subsawwy.com/backend.env

  tasks:
    - name: Check if env file exist
      ansible.builtin.stat:
        path: "{{ item }}"
      register: env_files
      with_items:
        - "{{ backend_env_path }}"
      
    - name: Fail if env file don't exist
      fail:
        msg: "Required .env file not found. Please ensure {{ backend_env_path }} exists."
      when: not env_files.results[0].stat.exists

    - name: Create network
      community.docker.docker_network:
        name: subsawwy_net
        driver: bridge
        state: present

    - name: Log into private registry
      community.docker.docker_login:
        registry_url: registry.keireira.com
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        reauthorize: true

    - name: Deploy backend (SS-API)
      community.docker.docker_container:
        name: SS-API
        image: registry.keireira.com/subsawwy-backend:latest
        state: started
        restart_policy: always
        recreate: true
        networks:
          - name: subsawwy_net
        ports:
          - "127.0.0.1:1337:1337"
        env_file: "{{ backend_env_path }}"

    - name: Clean up old images
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: true