name: Build & Deploy Entire SS

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKER_REGISTRY_USERNAME:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      ANSIBLE_HOST:
        required: true
      ANSIBLE_PORT:
        required: true
jobs:
  build-ss-web:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: registry.keireira.com
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
         
    - name: Build
      working-directory: ./web
      run: docker build --file Dockerfile --tag "registry.keireira.com/subsawwy-web:latest" .

    - name: Publish
      run: docker push "registry.keireira.com/subsawwy-web:latest" 

  build-ss-api:
    runs-on: octocat-1

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: registry.keireira.com
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
         
    - name: Build
      working-directory: ./backend
      run: |
        docker build --file Dockerfile \
          --tag "registry.keireira.com/subsawwy-backend:latest" . \
          --build-arg API_HOSTNAME=$API_HOSTNAME \
          --build-arg API_PORT=$API_PORT

    - name: Publish
      run: docker push "registry.keireira.com/subsawwy-backend:latest" 

  build-ss-landing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: registry.keireira.com
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
         
    - name: Build
      working-directory: ./landing
      run: docker build --file Dockerfile --tag "registry.keireira.com/subsawwy-landing:latest" .

    - name: Publish
      run: docker push "registry.keireira.com/subsawwy-landing:latest"

  deploy:
    needs: [build-ss-web, build-ss-api, build-ss-landing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key to server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ansible-deploy
          chmod 600 ~/.ssh/ansible-deploy
          if ! ssh-keygen -F ${{ secrets.ANSIBLE_HOST }} -p ${{ secrets.ANSIBLE_PORT }}; then
            ssh-keyscan -p ${{ secrets.ANSIBLE_PORT }} ${{ secrets.ANSIBLE_HOST }} >> ~/.ssh/known_hosts
          fi
          
      - name: Verify inventory
        run: ansible production --list-hosts -i ansible/inventory.ini

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy-all.yml \
            -e "docker_username=${{ secrets.DOCKER_REGISTRY_USERNAME }}" \
            -e "docker_password=${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
