name: subsawwy-all-build

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKER_REGISTRY_USERNAME:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true

jobs:
  build-fe:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: registry.keireira.com
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
         
    - name: Build
      working-directory: ./web
      run: docker build --file Dockerfile --tag "registry.keireira.com/subsawwy-web:latest" .

    - name: Publish
      run: docker push "registry.keireira.com/subsawwy-web:latest" 

  build-api:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: registry.keireira.com
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
         
    - name: Build
      working-directory: ./backend
      run: |
        docker build --file Dockerfile \
          --tag "registry.keireira.com/subsawwy-backend:latest" . \
          --build-arg API_HOSTNAME=$API_HOSTNAME \
          --build-arg API_PORT=$API_PORT

    - name: Publish
      run: docker push "registry.keireira.com/subsawwy-backend:latest" 

  build-landing:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: registry.keireira.com
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
         
    - name: Build
      working-directory: ./landing
      run: docker build --file Dockerfile --tag "registry.keireira.com/subsawwy-landing:latest" .

    - name: Publish
      run: docker push "registry.keireira.com/subsawwy-landing:latest" 