name: Build Frontend Web App

on:
  push:
    paths:
      - asse-web/**
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKER_REGISTRY_USERNAME:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true

jobs:
  build-fe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: registry.keireira.com
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
         
    - name: Build
      working-directory: ./asse-web
      run: docker build --file Dockerfile --tag "registry.keireira.com/subsawwy-web:latest" .

    - name: Publish
      run: docker push "registry.keireira.com/subsawwy-web:latest" 