name: Build & Deploy

on:
  push:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKER_REGISTRY_USERNAME:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      ANSIBLE_HOST:
        required: true
      ANSIBLE_PORT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: registry.keireira.com
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build
      run: docker build --file Dockerfile --tag "registry.keireira.com/subsawwy-web:latest" .

    - name: Publish
      run: docker push "registry.keireira.com/subsawwy-web:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Add SSH key to server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ansible-deploy
          chmod 600 ~/.ssh/ansible-deploy
          if ! ssh-keygen -F ${{ secrets.ANSIBLE_HOST }} -p ${{ secrets.ANSIBLE_PORT }}; then
            ssh-keyscan -p ${{ secrets.ANSIBLE_PORT }} ${{ secrets.ANSIBLE_HOST }} >> ~/.ssh/known_hosts
          fi

      - name: Verify inventory
        run: ansible production --list-hosts -i ansible/inventory.ini

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml \
            -e "docker_username=${{ secrets.DOCKER_REGISTRY_USERNAME }}" \
            -e "docker_password=${{ secrets.DOCKER_REGISTRY_PASSWORD }}"